/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TrabalhoFinal;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import TrabalhoFinal.Produto;
import javax.accessibility.AccessibleContext;
import TrabalhoFinal.TelaExibir3;
public class TelaCadastrar2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    private TelaExibir3 telaExibir;
    private Produto produto;
    
    
    public TelaCadastrar2() {
        initComponents();
        this.setSize(680, 580);
    }  
     



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Novo = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        quantidade = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        VlCompratext = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        vlVendaText = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        obs = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JFormattedTextField();
        fornecedor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Cadastro de Produto");
        getContentPane().setLayout(null);

        Novo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Novo.setText("Novo");
        Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovoActionPerformed(evt);
            }
        });
        getContentPane().add(Novo);
        Novo.setBounds(10, 210, 110, 27);

        Salvar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Salvar);
        Salvar.setBounds(10, 250, 110, 27);

        Cancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar);
        Cancelar.setBounds(10, 300, 110, 27);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Código:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 210, 50, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Produto:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 265, 80, 20);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        getContentPane().add(nome);
        nome.setBounds(270, 260, 380, 30);

        quantidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "Outro valor" }));
        getContentPane().add(quantidade);
        quantidade.setBounds(270, 310, 90, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Quantidade:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 315, 90, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("ValorCompra: R$");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 355, 120, 20);

        VlCompratext.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        VlCompratext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VlCompratextActionPerformed(evt);
            }
        });
        getContentPane().add(VlCompratext);
        VlCompratext.setBounds(310, 350, 90, 30);

        jLabel8.setText("Fornecedor:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 310, 100, 30);

        vlVendaText.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        vlVendaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlVendaTextActionPerformed(evt);
            }
        });
        getContentPane().add(vlVendaText);
        vlVendaText.setBounds(540, 350, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Valor  Venda: R$");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 350, 120, 30);

        jLabel10.setText("Descrição:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(180, 380, 90, 30);

        obs.setColumns(20);
        obs.setRows(5);
        jScrollPane1.setViewportView(obs);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 410, 480, 87);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrabalhoFinal/Captura de tela de 2016-11-24 15_31_39.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 360, 190);

        codigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));
        getContentPane().add(codigo);
        codigo.setBounds(270, 210, 109, 30);

        fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorActionPerformed(evt);
            }
        });
        getContentPane().add(fornecedor);
        fornecedor.setBounds(480, 310, 180, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TrabalhoFinal/61368_Papel-de-Parede-Flores-Azuis_1024x768.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 720, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovoActionPerformed
        this.limparCampos();
    }//GEN-LAST:event_NovoActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed

        String codigo = this.codigo.getText();// numero
        String nome = this.nome.getText();
        int quantidade =this.quantidade.getSelectedIndex();
        String fornecedor = this.fornecedor.getSelectedText();
        String vlCompra= this.VlCompratext.getText(); // numero
        String vlVenda = this.vlVendaText.getText();//numero
        String obs  = this.obs.getText();

        float vc = 0.0f;
        float vv = 0.0f;

        try {
            vc = Float.parseFloat(vlCompra);
            vv = Float.parseFloat(vlVenda);
        } catch (Exception e) {

            JOptionPane.showMessageDialog(this,
                "E necessario preencher todos os campos.");

            return;

        }
        
        
        
        Produto p = this.produto;

        if (p == null) {

            // criar um objeto produto
            p = new TrabalhoFinal.Produto(obs,
                                          nome, 
                                          quantidade, 
                                          fornecedor,
                                          vv, 
                                          vc, 
                                          obs);

        }

        // chamar o controle para tentar cadastrar

        ControllerCadastro controlador = new ControllerCadastro();
        if (this.produto == null) {

            if (controlador.cadastrarProduto(p)) {
                JOptionPane.showMessageDialog(this, "Cadastrado com sucesso");
                this.dispose();
                //telaExibir.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Cadastro Não realizado. "
                    + "\n\nFaltando dados");
            }
        }
       
        this.limparCampos();

        }
        private void formWindowActivated(java.awt.event.WindowEvent evt) {
            // TODO add your handling code here:

            if (this.produto != null) {
                carregarProdutoNosCampos();
            }

        }
        public void limparCampos() {
            this.codigo.setText("");
            this.nome.setText("");
            this.fornecedor.setText("");
            this.VlCompratext.setText("");
            this.vlVendaText.setText("");

    }//GEN-LAST:event_SalvarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed

        new TelaExibir3().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void vlVendaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlVendaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vlVendaTextActionPerformed

    private void fornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fornecedorActionPerformed

    private void VlCompratextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VlCompratextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VlCompratextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Novo;
    private javax.swing.JButton Salvar;
    private javax.swing.JFormattedTextField VlCompratext;
    private javax.swing.JFormattedTextField codigo;
    private javax.swing.JTextField fornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JTextArea obs;
    private javax.swing.JComboBox quantidade;
    private javax.swing.JFormattedTextField vlVendaText;
    // End of variables declaration//GEN-END:variables
private void carregarProdutoNosCampos() {
        
        codigo.setText(this.produto.getCod()+"");
        nome.setText(this.produto.getNome()+ "");
        quantidade.setSelectedIndex(0);
        VlCompratext.setText(this.produto.getVlCompra()+"");
        VlCompratext.setText(this.produto.getVlVenda()+"");
        obs.setText(this.produto.getObserv()+"");
       
        
        
}  
}
